### ISSUE TITLE
Documentation - ReadTheDocs

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#12]
Setup inline code documentation and ReadTheDocs integration.

**Comment by kersulis** [comment]
Are you partial to Markdown, or would you like to go with reST/Sphinx like JuMP?

**Comment by mlubin** [comment]
I'd discourage using RTD. JuMP is gradually migrating away in favor of github pages.

**Comment by kersulis** [comment]
Good to know. Any technical reason?

So the JuMP doc site will be built by Sphinx and pushed to gh pages in the future?

(Pardon all the questions, I'm working on documentation for another project so I'm curious.)

**Comment by mlubin** [comment]
Right now we push manually to gh pages: http://www.juliaopt.org/JuMP.jl/0.14/ https://github.com/JuliaOpt/JuMP.jl/blob/master/howto_release.txt

We're moving away from RTD because it's simply been broken on branches for us for more than a year with no fix (https://github.com/rtfd/readthedocs.org/issues/1617).

**Comment by kersulis** [comment]
That's too bad about RTD. The current release process seems like a good workaround though.

The more I use Sphinx, the more I like it. It's tough to walk away from the simplicity of Markdown, but you gain so much.

**Comment by ccoffrin** [comment]
I am pretty agnostic to Sphinx and MD, the key bonus in going with Sphinx is in-line docs auto generating API docs.  Is this feature not available in Julia?

**Comment by mlubin** [comment]
See https://github.com/JuliaDocs/Documenter.jl
