### ISSUE TITLE
Use "!" for fcns that modify inputs

### ISSUE THREAD

**Issue by kersulis** [lanl-ansi/PowerModels.jl#24]
Functions that modify their inputs typically [have an exclamation point](http://docs.julialang.org/en/release-0.4/manual/style-guide/#append-to-names-of-functions-that-modify-their-arguments) at the end of their names, to help them stand out. I can make a PR if you would like to adopt this convention.

**Comment by mlubin** [comment]
As a counterpoint we've avoided these in JuMP because they look confusing to non-Julia programmers and we want JuMP code to be something pretty that you can put on a slide without needing to explain too much. MathProgBase has them because it's meant for people who know what they're doing. So there's definitely a decision to be made on whether they're wanted here or not.

**Comment by ccoffrin** [comment]
Both are good points.  In this case, nearly every function would have ! appended to.  Let me think on it.

**Comment by ccoffrin** [comment]
After thinking on this for a bit, my current preference is to not use ! for now.  My rational is,

1. I do agree with @mlubin's point, many users of this code may be non-julia experts.  Having to put ! on everything will seem confusing / tedious to them.
2. One of the design goals is to make PowerModels _feel_ like JuMP.  So the abstractions will seem familiar to users who know JuMP.  Hence, we should follow the JuMP convention and not to use !.

In the future, if we end up having a "core" abstraction layer, like MathProgBase, we will use the Julia ! convention.

**Comment by kersulis** [comment]
Makes sense, I think this is the right call.
