### ISSUE TITLE
Dependency on DataStructures.jl

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#255]
I just noticed this dependency on DataStructures.jl
https://github.com/lanl-ansi/PowerModels.jl/blob/e02b5143b4a2409312aedd787bfe90c7c63b4a33/src/io/pti.jl#L6

It is a best practice to put `using` calls in the root of the package 
https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/PowerModels.jl

Also the base `REQUIRE` should include all package dependencies.

In this case, I am wondering if it is worthwhile to add the dependency on DataStructures rather than the data structures that are in Base.

**Comment by ccoffrin** [comment]
In this use case, what additional benefits does `OrderedDict` give us, over arrays of tuples?

**Comment by pseudocubic** [comment]
For me, really code simplicity, which prevents having to use numbered indices, which can make debugging difficult and reduce readability, is really the big benefit. Memory layout is typically another benefit to OrderedDicts, but here I admit that is pretty negligible. Furthermore, because it is a Dict, it is easier to iterate over keys or values only, and lookup for a specific key is easier, because instead of having to search through each item of an array, there is a hash table, which is what I imagine will be useful when adding default values, or better supporting parsing of PTI files.

**Comment by ccoffrin** [comment]
Having a look at, `get_pti_dtypes`, it appears that its `OrderedDict` return type is only used in for loops, so an array of `{String,Type}` tuples would do the job without issue.  After that, I am not seeing any other place where the `OrderedDict` functionality is leveraged, did I miss something?

**Comment by pseudocubic** [comment]
As far as I know you are correct about the current use case, but when implementing this data structure I was trying to consider potential future use cases as well. The one case in particular that I had in mind was where I would need to call for a specific key to get a default value or check that a data type hasn't changed (during debugging, which I have used, although not in unit tests obviously), and not just use them all in order. In that case, having an array would be disadvantageous since I would need to search the array every time I want to use a particular key. I thought of OrderedDicts because they are an existing data structure made for this type of use case, and I was pointed to DataStructures.jl via a Julia GitHub issue (unfortunately indicating to me that the Julia authors probably don't have any intention of adding such a structure).
