### ISSUE TITLE
Owner data in three winding transformer tests

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModels.jl#292]
In these test cases,
```
three_winding_test.raw 
three_winding_test_2.raw 
three_winding_mag_test.raw
```
The owner information seems to be missing on the generators.  For example, at the end of each component line I would expect to see something like, `0,1.0000,   0,1.0000,   0,1.0000,  0,1.0000`

I am wondering if these field are optional in a PSSE/PTI data file or not, thoughts?

**Comment by pseudocubic** [comment]
It looks like by default O2-O4 are 0, and F1-F4 are 1.0, as you expect, but O1 should be bus I. 

However, from the parser's point of view, omitting them wouldn't cause any problems because they are the last fields, and there is nothing in terms of data that we need (we are not currently using owner data for anything).

It is interesting that these fields are missing though, since the template for these tests was derived from a case in another PTI file which was presumed to be valid.

**Comment by ccoffrin** [comment]
I think the root of the question is, is omitting these fields still valid PTI?  I don't see any hint in the specification document, do you?

It is convenient that our parser is robust to missing data, but it's probably a good idea to raise a warning when a component is missing something that the PTI format is expecting.

**Comment by pseudocubic** [comment]
That's a good question, I'm not sure if it's considered a valid PTI file or not, I've seen some examples obviously without those fields, but I agree that a warning might be a good way to go, I will see to adding that to the parser.
