### ISSUE TITLE
Modeling of linear cost functions

### ISSUE THREAD

**Issue by lthurner** [lanl-ansi/PowerModels.jl#421]
As discussed in #415, linear polynomial cost functions are always modeled as quadratic functions:

>In the case of the polynomial cost model (i.e. model 2), internally PowerModels assumes it is at least a quadratic function; so your implementation cost = [0.0, c1, c0] is what PowerModels expects for a linear function.
If you run into any disadvantages of this more general function let me know and I can look into adding an objective that is more suitable for linear cost functions.

I am opening a new issue for this because I now ran into a problem with this representation. I was playing around with different solvers, and tried to solve a DC OPF with GLPK instead of Ipopt. This results in the error 

> Solver does not support quadratic objectives

Even though I defined a linear cost function (which was then converted into a quadratic cost function with c2=0 as discussed above).

This can be reproduced with:

```
using PowerModels
using GLPKMathProgInterface
result = PowerModels.run_dc_opf("case5_linear.m", GLPKSolverLP(presolve=true))
```

where the gencost function in case5 is replaced with

> mpc.gencost = [
	2	 0.0	 0.0	 2	   14.000000	   4.000000;
	2	 0.0	 0.0	 2	   15.000000	   0.000000;
	2	 0.0	 0.0	 2	   30.000000	   0.000000;
	2	 0.0	 0.0	 2	   40.000000	   0.000000;
	2	 0.0	 0.0	 2	   10.000000	   0.000000;
];

I also compared runtimes of PYPOWER and PowerModels, and while the AC OPF seems to be significantly faster (in most cases I tested about a factor of 10), this doesn't seem to be the case for the DC OPF. In fact, I tested it with a transmission system of Germany (about 500 buses, 600 lines) and while the PYPOWER DC OPF takes about 250ms, PowerModels takes 2.2s to solve the problem. I am wondering if this might be because of the (pseudo-)quadratic cost functions that introduce a non-linearity into the linearized problem?

**Comment by ccoffrin** [comment]
I should start with a remark that my group is very rarely using the DC power flow.  We mostly use AC and convex relaxations; so very fast and reliable AC solves have been our focus, thus far.  I am suer there are many improvements that can be made in the DC power flow.

Regarding the LP solvers (e.g. GLPK), I am aware of this annoyance, but you are first person to bring it up.  We can surely add a feature to PowerModels so that an LP solver can be used for the case of DC models with linear objectives.  Let me think about how to best support this.

Regarding your performance test.  What QP solver did you use to do this test in PowerModels?  The last time I did this test, [see this report](https://arxiv.org/pdf/1711.01728.pdf), I was seeing solve times that were most often below a second.  If we can identify that the runtime issue is in the LP solver and not setting up the mathematical program, then there are a few performance improvements I can make DC power flow model that should speed it around 2x-10x.

**Comment by rb004f** [comment]
In GasGridModels, in the cases where we had a quadratic constraint or objective that could have a 0 on the quadratic term, we do a quick test for this and post the constraint/objective in its linear form when that condition holds and the quadratic form when it does hold.  Didn't seem to clutter the code too much.  Our main use case there is a quadratic constraint with equality that is turned into an inequality in the relaxations.  We wanted to preserve the equality condition in the cases when the constraint was actually linear. 

see https://github.com/lanl-ansi/GasGridModels.jl/blob/master/src/form/qp.jl

So, that is a possible solution for the PowerModels objective.
