### ISSUE TITLE
Extracting PD, QD from network_data["load"] confusion

### ISSUE THREAD

**Issue by jchen975** [lanl-ansi/PowerModels.jl#544]
Hi, this might be a really dumb question but I'm new to PowerModels and took a look at previous issues and documentation but didn't really find anything: 

I'd like to extract the `pd`, `qd` values of all the PQ buses in a Matpower case file. However, as an example, for non trivial cases such as case30, the `network_data["bus"]` dictionary has 30 entries as expected, but `network_data["load"]` dictionary has only 20 entries and I'm not sure what the keys stand for. For the `bus` dictionary, each key corresponds to the `bus_i` but that doesn't seem to be the case for `load` dictionary. Inside each entry, the `load_bus` corresponds to the `bus_i` value in the Matpower file and the `pd`, `qd` values are what I'm looking for. Similar discrepancies exist in other non trivial cases as well. Could anyone clarify on how I can proceed?

**Comment by ccoffrin** [comment]
Hi, this part of the docs discusses the differences of the PowerModels data and Matpower data,

https://lanl-ansi.github.io/PowerModels.jl/stable/network-data/

Other than that, I am not sure I follow your question.  It sounds like you have good understanding of how the data works.

**Comment by jchen975** [comment]
Hi Mr. Coffrin, thanks for your reply. What I meant is, the `network_data["load"]` seem to be missing entries after I get the `network_data` by parsing a Matpower case file. For example, from the `case30.m`, this is what I get in the `load` dictionary and it seems to be missing keys 22~30: 
![Capture](https://user-images.githubusercontent.com/47189952/59612710-94392c80-90eb-11e9-82c4-b80750d626e3.PNG)
The other confusion I had was that each key in the `load` dictionary doesn't necessarily correspond to its entry's `load_bus` field, for example, from the same case file: 
![Capture1](https://user-images.githubusercontent.com/47189952/59612961-07db3980-90ec-11e9-93b8-0e35793aea75.PNG)

What I'm trying to do is to extract the PD and QD fields of each PQ bus, so for larger case files available in Matpower, I'm not sure I understand the `load` dictionary keys and why it's "missing" entries. Hopefully you could clarify that, thanks!

**Comment by ccoffrin** [comment]
Got it.  The key point here is that PowerModels supports loads as explicit components that are separate from buses.  So a bus can have none, 1, or many loads.  The load objects have unique ids, which are independent from the bus ids.  These load object ids are the keys in the load dictionary and the index value.  The "load_bus" value tells you which bus id the load is connected to.

Because buses can have no loads in PowerModels, when parsing Matpower data, loads with pd=0.0 and qd=0.0 are filter out.

Does that help?

For future reference, questions are best made on [Discourse](https://discourse.julialang.org/c/domain/opt), issues are best for bug reports and feature requests.

**Comment by jchen975** [comment]
Yes, thanks very much for your help!
