### ISSUE TITLE
DC power flow unexpected results

### ISSUE THREAD

**Issue by FlorianShepherd** [lanl-ansi/PowerModels.jl#612]
I compared the pandapower and PowerModels.jl AC and DC power flow results for a small test grid (4 buses, 1 transformer, 2 lines). The AC results are equal. But when comparing DC results I noticed that the DC power flow voltage angle (Va) results differ. The difference is huge even for the small test case.

First I assumed it was a conversion error (from pandapower -> PowerModels.jl), but when forcing "br_r" values of all branches to zero, the results are equal:

```
    if model == "DCPPowerModel"
            for (i, branch) in pm["branch"]
                branch["br_r"] = 0.
            end
    end
    result = PowerModels.run_pf(pm, model, solver,
                                    setting = Dict("output" => Dict("branch_flows" => true)))
```

The matpower, pypower and pandapower implementations should not differ. Also I verified the formulas and "Wood, Allen - Power generation, operation and control" to be sure. Va should be independent of "br_r" since "br_r << br_x". However, on page 274 it is written that "Bik" is either "- 1 / br_x" or "- br_x / (br_r² + br_x²)" (I'm a little bit confused). Nevertheless, this leads me to the following two possibilities: 

1. The DC power flow results of PowerModels.jl are not correct, since "br_r" must not be considered in the DC power flow
2. The PowerModels.jl implementation just differs, since br_r is considered intentionally

I'm about to test other grids as well. I already noticed that the DC results of a (modified) version of the RTS (96 bus) grid still differ "a little" when forcing br_r = 0. I haven't figured out why yet. Maybe this is still a conversion error. 

P.S.: Thanks again @ccoffrin for the help via mail some weeks ago. I could fix a lot of conversion errors and also some bugs in the pandapower OPF :) The TNEP optimization works really well!

**Comment by FlorianShepherd** [comment]
> I'm about to test other grids as well. I already noticed that the DC results of a (modified) version of the RTS (96 bus) grid still differ "a little" when forcing br_r = 0. I haven't figured out why yet. Maybe this is still a conversion error.

I could reproduce the error with the four bus test grid. The reason seems to be the TAP value of the transformer. In "makeBdc()" the tap value of each transformer is considered by `b = b / tap` like this:
```
    stat = branch[:, BR_STATUS]               ## ones at in-service branches
    b = stat / branch[:, BR_X]                ## series susceptance
    tap = ones(nl)                            ## default tap ratio = 1
    i = find(real(branch[:, TAP]))               ## indices of non-zero tap ratios
    tap[i] = real(branch[i, TAP])                   ## assign non-zero tap ratios
    b = b / tap
```

If I change the tap value to any value before running a DC power flow in julia / PowerModels:
```
    for (i, branch) in pm["branch"]
        branch["br_r"] = 0.
        branch["tap"] = 10.
    end
```
The result (va) doesn't change at all (in pandapower / pypower it does).

The AC power flow results are equal in pandapower and PowerModels.jl when changing the TAP.

**Comment by ccoffrin** [comment]
@FlorianShepherd glad to hear you are still enjoying PowerModels and thanks for for taking the time to post this issue.  Both of these points are known to me. 

- The `1/br_x` vs `- br_x / (br_r² + br_x²)` distinction is by design in PowerModels and I use the later.  There is a discussion of my motivations for this here, https://github.com/lanl-ansi/PowerModels.jl/issues/597
- Concerning transformer phase shifts in the DC model, this is a known problem and discussed here, https://github.com/lanl-ansi/PowerModels.jl/issues/422.  There is a prototype for how I plan to fix this in a stale branch called `tr-tp-models`.   It has not been a super high priority thus far, but if it is causing you issues I will increase its priority.
- Concerning transformer tap ratios, I don't think it makes a lot sense to incorporate those into a traditional DC model becouse this parameter primarily impacts voltage magnitude and not phase angles.

Part of the PowerModels design philosophy is that the default DC Power Flow should be a very simple variant of an active-power-only model.  More detailed models like DCPLL or LPACC are defined as more accurate approximations that better handle losses and reactive power.  I don't find that there is sufficient consistency in DC Power Flow models to claim that one is "standard" and another is not (I am open to debate on this claim).  Hence, inconsistencies using this model across tools should be expected.  If you like, we can add a DCMPPowerModel that will exactly replicate what Matpower does as a non-default DC Power Flow model in PowerModels.

**Comment by FlorianShepherd** [comment]
Thanks @ccoffrin for this answer. This clarifies a lot for me. I haven't checked the closed issues too intensely and missed the issues you mentioned. Sorry!

> Part of the PowerModels design philosophy is that the default DC Power Flow should be a very simple variant of an active-power-only model.

This is a really good idea. I just noticed the difference when comparing TNEP results and the DC model works quite well in terms of convergence. However, the solver tells me sometimes it converged and when checking again in pandapower the line loading values were a little too high / the voltage angles differed. I just wanted to be sure that this is not a conversion error and that the models are the same. 

> I don't find that there is sufficient consistency in DC Power Flow models to claim that one is "standard" and another is not (I am open to debate on this claim). Hence, inconsistencies using this model across tools should be expected

I agree. I just didn't expect the difference. I always check https://lanl-ansi.github.io/PowerModels.jl/stable/formulation-details/ when I want to get quick information about the models. I think it would be good idea to add some hints like: 

The DCPPowerModel differs from the DC model of matpower in the following way:
1. The real part of the branch impedance values `br_r` are considered in the DC power flow instead of only the imaginary part `br_x`
2. The transformer `shift` is not yet considered 
3. The transformer tap is not considered

> It has not been a super high priority thus far, but if it is causing you issues I will increase its priority.

Thanks :) I don't think this is so urgent. The hint about the behaviour is sufficient (at least for me) I guess.

> If you like, we can add a DCMPPowerModel that will exactly replicate what Matpower does as a non-default DC Power Flow model in PowerModels.

I really like the idea of adding a "DCMPPowerModel" model. This makes it easier for other people to be able to compare the results, since I assume many people are using matpower and its (python) descendants. I'd like to do that / at least help (I'm not familiar with either Julia nor how to create a PowerModel). Maybe you can point me in the right direction where and how to start?

**Comment by ccoffrin** [comment]
@FlorianShepherd, sounds good.  I have added a note about this to the DCPPowerModel documentation, as you suggest.

Concerning `DCMPPowerModel` the steps are roughly as follows,
- In `core/types.jl` add a subtype of `AbstractDCPModel` named `AbstractDCMPPModel` and it's implementation, `DCMPPowerModel`
- In `form/dcp.jl` add a version of `constraint_ohms_yt_from`  that uses the `DCMPPowerModel` type and modify the constraint to match Matpower's version (you will need to derive the value of `1/x`, and transformer shift from the data arguments which are in a different form)
- Add a test to `test/opf.jl`, this test should be more specific than the usually OPF tests because we want to make sure that the values of the phase angles do not change significantly.

If you also want to consider the TNEP version of `DCMPPowerModel` more functions will need to be overloaded, e.g. `constraint_ohms_yt_from_ne`.

**Comment by FlorianShepherd** [comment]
Cool, thank you, especially for the description :)

I'm on it, but already get stuck since the function inside form/dcp.jl looks like this:

```
function constraint_ohms_yt_from(pm::AbstractDCPModel, n::Int, c::Int, f_bus, t_bus, f_idx, t_idx, g, b, g_fr, b_fr, tr, ti, tm)
    p_fr  = var(pm, n, c,  :p, f_idx)
    va_fr = var(pm, n, c, :va, f_bus)
    va_to = var(pm, n, c, :va, t_bus)

    JuMP.@constraint(pm.model, p_fr == -b*(va_fr - va_to))
    # omit reactive constraint
end
```
I already gets `-b`. When I search for its definition I find it in `data.jl` which looks like this:

```
function calc_branch_y(branch::Dict{String,<:Any})
    y = pinv(branch["br_r"] + im * branch["br_x"])
    g, b = real(y), imag(y)
    return g, b
end

```

I thought about adding (or something similar):

```
function calc_branch_y_dcmp(branch::Dict{String,<:Any})
    b = -pinv(branch["br_x"])
    g = 0.
    return g, b
end
```

But then in `constraint_template.jl` everything is derived from `AbstractModel` and is not model specific. (example: `function constraint_ohms_y_to(pm::AbstractPowerModel, i::Int; nw::Int=pm.cnw, cnd::Int=pm.ccnd)`)

From my limited understanding I'd assume now that I have to change a lot of functions. Or is possible to get `br_x` inside `constraint_ohms_yt_from` somehow from the `pm` input?

(I apologize for my ignorance)

**Comment by ccoffrin** [comment]
The simple solution is to recompute `br_x` inside of `constraint_ohms_yt_from` along these lines, `x = -b/(b^2 + g^2)`, but you should double check my math on that.  You will have to do something similar for recovering the transformer phase shift as well.

**Comment by FlorianShepherd** [comment]
A colleague (thanks Maryam!) and me figured it out. The solution is this:

```
function constraint_ohms_yt_from(pm::AbstractDCMPPModel, n::Int, c::Int, f_bus, t_bus, f_idx, t_idx, g, b, g_fr, b_fr, tr, ti, tm)
    p_fr  = var(pm, n, c,  :p, f_idx)
    va_fr = var(pm, n, c, :va, f_bus)
    va_to = var(pm, n, c, :va, t_bus)

    # get b only based on br_x (b = -1 / br_x)
    r = pinv(sqrt(g^2 + b^2))
    theta = -atan(b / g)
    b = pinv(r * sin(theta))
    # divide by tap 
    b /= tm
    
    JuMP.@constraint(pm.model, p_fr == b*(va_fr - va_to))
    # omit reactive constraint
end
```

I added a (power flow) test and validated the results in pandapower. Seems to work fine: f57eb5debeb2fae839674acd070e97ec1d66f739

I can add another test for OPF and tnep. 

What is missing is the phase shift. For this I have to find out where "Pbus" is created and how the results are being read to the solution Dict(). If you have another hint, that would be great :)

**Comment by ccoffrin** [comment]
Would this work?
```
x = -b / (g^2 + b^2)
ta = atan(ti / tr)
JuMP.@constraint(pm.model, p_fr == (va_fr - va_to - ta)/(x*tm))
```

**Comment by frederikgeth** [comment]
(FYI, writing `atan(ti,tr)` instead of `atan(ti/tr)` [avoids problems](https://docs.julialang.org/en/v1/base/math/#Base.atan-Tuple{Number}) with edge cases.)

**Comment by FlorianShepherd** [comment]
Works perfect :) (and looks like black magic what you have done. Thank you @ccoffrin and @frederikgeth !). 

I added a test for TNEP and changed the PF test including the shift deaa02e505e8ae572abdffb1601e9a4fc3bb4068 . I'll open a pull request.

Just one more thing. I noticed that when I store the matpower file like this:
```
     io = open("./pp_simple4_tnep.m", "w")
     PowerModels.export_matpower(io, pm)
     close(io)
```
The shift and tap value are not stored correctly, but set to 0.0. I checked `matpower.jl`, which says:
`branch["transformer"] ? branch["tap"] : 0`, but 'transformer' is set to true in my (from pandapower converted) input data. Is this tested?

**Comment by ccoffrin** [comment]
Concerning the transformer parameter, I am not sure what could cause this issue.  We test the bidirectional invertibility of matpower files when our parser reads them in, which should be checking that transformer parameters are exported properly.  Could it possibly with a python-based json writer?  For example setting a value fo `True` in the JSON document probably parses as a string instead of a bool.

**Comment by FlorianShepherd** [comment]
I read it like this:
```
import JSON

pm = Dict()
open(json_path, "r") do f
        pm = JSON.parse(f)  # parse and transform data
end
```

inside the *.json file the transformer is defined like so:

```
{"index": 3, "transformer": true, "br_r": 0.047996851199999996, "br_x": 0.15263247010263137, "g_fr": 0.0002999978398583073, "g_to": 0.0002999978398583073, "b_fr": -6.868263343252991e-09, "b_to": -6.868263343252991e-09, "rate_a": 250.0, "rate_b": 250.0, "rate_c": 250.0, "f_bus": 1, "t_bus": 2, "br_status": 1, "angmin": -1.0471975511965976, "angmax": 1.0471975511965976, "tap": 1.05, "shift": 0.5235987755982988}
```

**Comment by ccoffrin** [comment]
That looks reasonable, so how can this line fail in the matpower export `branch["transformer"] ? branch["tap"] : 0`?

**Comment by FlorianShepherd** [comment]
It was indeed a casting error from pandapower -> pm. I just confused the files (the pasted *.json data above is wrong). Sorry for that, my bad. The exchange between pandapower, PowerModels.jl, julia and python is a little bit cumbersome...

Saving now works fine and I fixed a bug in pp. Thanks :+1:
