### ISSUE TITLE
Proposal for more flexible result dictionaries

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/PowerModels.jl#627]
Formulations currently return different variable sets. E.g. SOC/SDP relaxations don't return voltage angles whereas ACP/ACR/ACT do. This was noted in https://github.com/lanl-ansi/PowerModels.jl/issues/6. 

Nevertheless, if the result of a SOC/SDP relaxation formulation satisfies its exactness guarantees, you can uniquely recover the voltage angles. On the other hand, if the relaxation is not exact, but you want to explore the result, it is currently hard to inspect the optimised values of *all* variables (e.g. wr and wi are not returned). 

Some observations
- ACP, ACR and ACT all return polar voltages
- To derive branch current, you actually want rectangular voltages
- To post-process from variable spaces P+jQ, W_i=U_i(U_i)* (e.g. includes common BFM and BIM forms) you need to know the reference bus and its reference angle (matpower assumes this is 0, but OpenDSS does not)

There is a use case for utilities to simplify conversion between variable spaces for formulations that are, or can be exact. I see 3 forms to standardize conversion utilities on
1. rectangular current and rectangular voltage
2. rectangular power and rectangular voltage
3. rectangular power and rectangular lifted voltage _+ reference bus angle(s)_
Alternatively, forms 1 and 2 can be defined with polar voltages (it adds a few redundant steps to sequential conversions, e.g. 3->1). 

Conversion between 1 and 2, and from 2 to 3 can be done node branch by branch/node by node in any order, i.e. it could be integrated in `solution_builder`. However from 3 to 2 you need to start from reference bus(es) and progress from there (order matters). This isn't easily integrated in `solution_builder`.

A mapping to existing formulations is
1. IVR
2. ACP, ACR, ACT, QC
3. SOCWR, SOCBF, SDPWRM, (QC?)

I see use cases for the following
- adding an option where each formulation returns _all_ of its variables
- by default a formulation returns the variables as defined in the above mapping (i.e. current situation)
- If you want to convert to another variable space, you need to call the right function yourself on a result dict. 

To do such conversion using only a result dict, you need a few things which currently are not stored in the result dict:
- from and to bus for each branch
- (list of) reference bus(es) and the(ir) angle(s)

I can spend a bit of time on this in the coming weeks, but I'm keen to get your thoughts before doing a lot of work.

**Comment by ccoffrin** [comment]
All good points.  Re-writing how solutions are built has been on the TODO list for many years, https://github.com/lanl-ansi/PowerModels.jl/issues/77.  I would recommend that we address that point first, as I think it will make these features much simpler to add.

The solution building re-write I currently have in mind, will walk the `pm.var` dict and build up a solution dict for all of the variables that are present there.  To do so, it will need to know how each variable maps to components (e.g. `:vm => :bus, :p => :branch`).  I am thinking a global dict for this with an optional argument for extending the mapping.  It will also need optional feature for skipping some variables (e.g. if you wish to omit line flows to save space or time writing out the solution).  Eventually, this very generic method will be moved up to Infrastructure models so that it is standard across packages.

I am thinking that this generic function will also accept some arbitrary post-processing functions (similar to the `ref_extensions` design).  These functions can add derived values and filter some values.  This would include projecting data back to the polar variable space and solution recovery like you are suggesting.

Concerning your point,
> To do such conversion using only a result dict, you need a few things which currently are not stored in the result dict:

The API for such a function should be `add_something!(result, data)`, so that you can get the required extra info from the `data`.  But I am not sure we will need these in the prosed new structure.

**Comment by frederikgeth** [comment]
Addressing #77 first is fine. I'll try to experiment next week to figure out how to do it per your suggestion. I like the idea of the `ref_extensions` to enable variable space conversion.

I don't like the idea of users having to collect two seperate dictionaries first, to run something like `add_something!(result, data)`. But it doesn't seem we'll need it with `ref_extensions`.

**Comment by ccoffrin** [comment]
Ok, thanks for that!

I should also note that I expect the `solution_extensions` functions will need to be parameterized by the AbstractPowerModel type so that the semantics can be adapted for different formulations / variable spaces.

I agreed the `add_something!(result, data)` may be a moot point now.  That said, another pattern for this that you might find more appealing could be,
```
update_data!(data, result)
add_something!(data)
```

**Comment by frederikgeth** [comment]
Would you be comfortable with adding these (or similar) in that context?
```
AbstractMagnitudeVoltageModels => union of all types that have :vm as a variable
AbstractAngleVoltageModels => :va
AbstractRectangularVoltageModels => :vr, :vi
AbstractLiftedRectangularVoltageModels => :w
AbstractLiftedRectangularVoltageProductModels => :wr, :wi
AbstractActivePowerModels => :p 
AbstractReactivePowerModels => :q 
AbstractRectangularCurrentModels =>:cr, :ci
AbstractLiftedRectangularCurrentModels =>:ccr, :cci
```

**Comment by ccoffrin** [comment]
I am not sure what your proposal here is.  Are these union types?  Most of these seems to already be covered by existing types.  If you are proposing a type-restructure and/or rename, let's handle that independently from the topic of solution data wrangling.

Given the current type structure `AbstractReactivePowerModels` is redundant.  Everything that is not in `AbstractActivePowerModels` is in `AbstractReactivePowerModels`.

**Comment by ccoffrin** [comment]
note to self, `has_values(model)` should be tested before trying to read solution data.

See discussion here, https://github.com/JuliaOpt/Gurobi.jl/issues/274

**Comment by ccoffrin** [comment]
Note there is also a request to support variables that are "network-less"

**Comment by frederikgeth** [comment]
I reckon this one can be closed soon as well.
