### ISSUE TITLE
Storage Constraint 

### ISSUE THREAD

**Issue by hamidbardideh** [lanl-ansi/PowerModels.jl#704]
Dear Carleton

regarding the storage modelling at link below:
https://lanl-ansi.github.io/PowerModels.jl/stable/storage/

I am in doubt about the constraint number (20) considered  for the storage. can you please verify if it is correct, and in case, help me to understand it. Thanks in advance

Hamid

**Comment by ccoffrin** [comment]
Hi Hamid,

I have added some links to the implementation in the docs,
https://lanl-ansi.github.io/PowerModels.jl/dev/storage/

So that you can at least verify that the implementation matches the mathematical model.

To answer your question about understanding (20).  This is modeling a 4 quadrant DC to AC inverter with some copper losses (`Z*|I|`) and standby losses (`S^l`), the `sqc` is required to allow for a reactive power set point of the inverter.  Note that the active-power-only approximation of this model is much simpler, because all of the reactive power aspects are skipped.

We have a technical report about this model coming out later this week, which derives the model from first principals with detailed explanations.  I will post it in this issue once it is available.

**Comment by hakanergun** [comment]
Hi Carleton,

Should the copper losses not be (Z * | I |^2), I also see it being quadratic in the constraints themselves:
    JuMP.@NLconstraint(pm.model,
        sum(ps[c] for c in conductors) + (sd - sc)
        ==
        p_loss + sum(r[c]*(ps[c]^2 + qs[c]^2)/vm[c]^2 for c in conductors)
    )

**Comment by ccoffrin** [comment]
Good catch!  The docs were incorrect and the implementation is correct, I have fixed the docs.

**Comment by ccoffrin** [comment]
The detailed derivation of this model is now available here, https://arxiv.org/abs/2004.14768, and I have added a link to this in the docs as well.  Shall we close this issue?
