### ISSUE TITLE
Loading matpower files

### ISSUE THREAD

**Issue by fnbillimoria** [lanl-ansi/PowerModels.jl#731]
A noobie question. I attempted to run the quick start on Powermodels.jl using the case below resulting in the error below.   Am i supposed to download matpower cases or add the matpower package to run the instruction below?  The documentation as currently written suggests that the instruction below should work fine. 
 
run_ac_opf("matpower/case3.m", with_optimizer(Ipopt.Optimizer))

ERROR: SystemError: opening file "matpower/case3.m": No such file or directory

Many thanks
Farhad

**Comment by ccoffrin** [comment]
The problem here is that you need to specify a valid path to a Matpower file on your system.  The paths provided in the documentation are just examples.

One solution would be the following,
```
using PowerModels; using Ipopt

case_file = joinpath(dirname(pathof(PowerModels)), "..", "test", "data", "matpower", "case3.m")

result = run_ac_opf(case_file, Ipopt.Optimizer)
```
This loads a case file out of the PowerModels tests directory.  However, these files are only designed to test the software and are not good examples of power transmission networks for study.

I can recomend the network files that are curated as part of [PGLib-OPF](https://github.com/power-grid-lib/pglib-opf) or the [RTS-GMLC](https://github.com/GridMod/RTS-GMLC) case.

**Comment by fnbillimoria** [comment]
Many thanks @ccoffrin   I also had a question in relation to whether Powermodel.jl interfaces with Powersystems.jl and whether the data model is the same.  Is there a another forum you recommend for these types of questions, or should I raise it as a Github issue?

**Comment by ccoffrin** [comment]
No problem.  PowerModels is loosely related to PowerSystems.  The basic breakdown is,
- PowerSystems - data wrangling many data sources into a cohesive power network dataset
- PowerSimulations - uses PowerSystems data + PowerModels to simulate power system operations, focusing on commerical-grade network realism.
- PowerModels - high performance power network optimization, focuses more on academic R&D rather than realistic production quality tools.

I am happy to answer questions here but the best forum for general questions like this is https://discourse.julialang.org/.

**Comment by fnbillimoria** [comment]
Thank you!  one final question - is the PowerSystems data structure transferable to PowerModels?  I am looking at doing a combination of operations/transient simulatio with network optimisation, and would like to transfer data effectively between the two modules.

**Comment by ccoffrin** [comment]
I think there is some basic support to send PowerSystems data to PowerModels, but you would be best to ask the developers of that package about it.

**Comment by fnbillimoria** [comment]
Thank you!
