### ISSUE TITLE
Geographic location of buses

### ISSUE THREAD

**Issue by antonplietzsch** [lanl-ansi/PowerModels.jl#740]
Some power grid test cases include information on the geographic location of the buses. (See for example: https://electricgrids.engr.tamu.edu/electric-grid-test-cases/) From what I know, this information is not included in the Matpower file format.

However, we would like to use this geographical information to combine an analysis in `PowerModels` with a meteorological model. Would it be possible to support latitude and longitude of buses as additional fields in your network data dictionary?

This would also be helpful for writing a plotting function that draws the spatially embedded grid structure.

**Comment by ccoffrin** [comment]
One can add data to the PowerModels data dictionary. So you are free to add that information in and use it as you see fit.  PowerModels Matpower data parser supports user extensions, so that could be an easy way to encode and import lat/lon data, see https://lanl-ansi.github.io/PowerModels.jl/stable/network-data/#Working-with-Matpower-Data-Files

The package https://github.com/lanl-ansi/PowerModelsAnalytics.jl is where we are currently exploring different vizulization ideas.  That package is still fairly experimental, but I suggest you take a look there and see if a basic visualization could suit your needs.  Suggestions for that package are surely welcome.

**Comment by antonplietzsch** [comment]
Ah, great! I did not realise there is support for user extensions in the data parser. I think that's exactly what we need. Thanks a lot!
