### ISSUE TITLE
Small typo in documentation, math model

### ISSUE THREAD

**Issue by chengg04** [lanl-ansi/PowerModels.jl#771]
There is a small typo in the documentation. In line 58 of the math model [(Link)](https://github.com/lanl-ansi/PowerModels.jl/blame/master/docs/src/math-model.md#L58), the voltage product `|V_j|^2` should be divided by the transformation ratio product `|{T}_{ij}|^2`, which is missing.

**Comment by ccoffrin** [comment]
Hi @chengg04, it is hard for me to cross reference the `md` file with the rendered documentation. Can you tell me which equation number on this page, https://lanl-ansi.github.io/PowerModels.jl/stable/math-model/, has an issue?

**Comment by chengg04** [comment]
Sure. Sorry, should have done that. It's equation (10). I suppose the first term in right-hand side should be divived by `|T_{ij}|^2|`, like what was done in equation (9)?

**Comment by ccoffrin** [comment]
Eq. (10) looks good to me.  Transformers in the AC equations are asymmetrical, so that is the source of the difference between equations (9) and (10).  The point of commonality between (9) and (10) is actually the later term in the RHS which is `V_i * V_j / T_{ij}`.

The agree the equations are super weird, but they should be correct. I can recommend the Matpower manual for a nice derivation of this equation from a line diagram.

**Comment by chengg04** [comment]
Sorry, you are right. Thanks for the recommendation. I'll close this issue.
