### ISSUE TITLE
My own objective function

### ISSUE THREAD

**Issue by Sofibhatti** [lanl-ansi/PowerModels.jl#846]
I am trying to have my own objective function but when I edit the objective function and add a new solve function it doesn't update the file or solve and gives  UndefVarError: build_new_opf not defined  
Any help on how can I define my function in the powermodel function file and solve for the given cases

**Comment by ccoffrin** [comment]
I need a bit more detail about how you are setting up the problem to understand what the issue is.

As a reference have a look at this model which shows one way to override the objective function without changing much else, https://github.com/lanl-ansi/PowerModelsAnnex.jl/blob/master/src/pglib/sad.jl

**Comment by Sofibhatti** [comment]
I add a new function in src\prob\opf.jl like mentioned in the above example and call it my main function but it doesn't recognize it and gives the error  build_new_opf not defined
The function I run is solve_model(pm_data, pm_type, Ipopt.Optimizer, build_new_opf)

**Comment by ccoffrin** [comment]
I can't immediately see why that would not work. Can you post an minimal working example that reproduces the this error?

**Comment by ccoffrin** [comment]
Closing due to no clear action and lack of activity.
