### ISSUE TITLE
Ask the question about SOCP model calculations in PowerModels

### ISSUE THREAD

**Issue by lzq-zbc** [lanl-ansi/PowerModels.jl#883]
This is about the node voltage of the case30 node system result .
`Dict{String, Any}("24" => Dict{String, Any}("w" => 1.0832362187928963), "29" => Dict{String, Any}("w" => 1.0812709847217152), "1" => Dict{String, Any}("w" => 1.1025), "12" => Dict{String, Any}("w" => 1.1025), "4" => Dict{String, Any}("w" => 1.0684651855066591), "20" => Dict{String, Any}("w" => 1.0569507322974918), "2" => Dict{String, Any}("w" => 1.0964007249030407), "6" => Dict{String, Any}("w" => 1.0581861521184712), "25" => Dict{String, Any}("w" => 1.1025), "23" => Dict{String, Any}("w" => 1.1088481172851914), "22" => Dict{String, Any}("w" => 1.1050644151765718), "11" => Dict{String, Any}("w" => 1.073817903773396), "13" => Dict{String, Any}("w" => 1.1768880732715865), "5" => Dict{String, Any}("w" => 1.0740189136260763), "15" => Dict{String, Any}("w" => 1.0857517071673406), "27" => Dict{String, Any}("w" => 1.131647844882569), "28" => Dict{String, Any}("w" => 1.062577458468718), "16" => Dict{String, Any}("w" => 1.0798775024448224), "14" => Dict{String, Any}("w" => 1.0824179718595324), "21" => Dict{String, Any}("w" => 1.0951568521021453), "7" => Dict{String, Any}("w" => 1.05229689278175), "8" => Dict{String, Any}("w" => 1.039137371478708), "26" => Dict{String, Any}("w" => 1.0692514938095674), "17" => Dict{String, Any}("w" => 1.0694057277503932), "19" => Dict{String, Any}("w" => 1.0508043274057632), "10" => Dict{String, Any}("w" => 1.0828098450190384), "9" => Dict{String, Any}("w" => 1.0738178951337156), "18" => Dict{String, Any}("w" => 1.0590363397069589), "30" => Dict{String, Any}("w" => 1.052098034808632), "3" => Dict{String, Any}("w" => 1.0736934059294263))`
I am a novice, and I would like to ask if I can obtain the node voltage phase angle result information through the above results of the node voltage amplitude of the SOCP model or other results

**Comment by ccoffrin** [comment]
The best venue for a question like this is the Julia discourse forum, https://discourse.julialang.org/c/domain/opt/13

In general, there is no way to recover phase angle information from the most common SOCP relaxations because of how they lift the variable space to a higher dimension. There are some special cases, like when the network is a tree, then angles can be recovered in most cases.

Because solution recovery cannot be done in general, it is not an out-of-the-box feature in PowerModels and is left for users to implement as part of a more specific application context.

If you want to learn more about relaxations of the AC equations I can recommend this video series that I put together with @lroald, https://arxiv.org/abs/1807.07227
