### ISSUE TITLE
use of Pandapower network in PowerModels.jl

### ISSUE THREAD

**Issue by ArnaudRssl** [lanl-ansi/PowerModels.jl#909]
Hello,

I was using pandapower in my research to simulate power systems and i dscovered PowerModels with all the tools to implement my own optimizaiton formulation. in order to fully go on PowerModels.jl, i  have to reuse the network that i have used in pandapower (i.e. modified Oberrhein network). 
I tried a lot of different save in pandapower and parse in powermodels but nothing works. I have the feeling that there is a function already done but i don't find it in the documentation.

If someone can help me, it would be very nice.

Thanks in advance
Arnaud

**Comment by ccoffrin** [comment]
Hi Arnaud, this sounds more like a question for the pandapower developers on how to export pandapower data.

PowerModels supports reading network data in the Matpower v2 and PSSE v33 formats.  If pandapower can export to those data formats you should be good to go.  Otherwise, you may need to implement your own data translation tool.

**Comment by ArnaudRssl** [comment]
Hi Carleton,

Thank you for your very fast answer. Indeed i will write my own data translation tool... 
The joy of researchers I think !

I already saw your answers to several issues in PowerModels.jl and I would like to thank you for all the work accomplished !

Have a nice day,
Arnaud from Mons (Belgium)
