### ISSUE TITLE
Unconstrained reference bus in optimal power flow

### ISSUE THREAD

**Issue by SimonUlm** [lanl-ansi/PowerModels.jl#927]
I tested PowerModels.jl (the `SOCWRPowerModel`) on the [pg-lib](https://github.com/power-grid-lib/pglib-opf) test case [pglib_opf_case3_lmbd.m](https://github.com/power-grid-lib/pglib-opf/blob/master/pglib_opf_case3_lmbd.m) and noticed that the reference bus is not constrained to 1 p.u. during the optimisation but instead to the provided min and max values (e.g. 0.9 and 1.1 respectively).

Therefore, the results differ from the results obtained by [PandaModels.jl](https://github.com/e2nIEE/PandaModels.jl), since they tighten the min and max values for the reference bus.

Is this behaviour desired?

I am looking forward to a reply and am happy to provide further details if desired.

**Comment by ccoffrin** [comment]
Hi @SimonUlm. The default OPF problem specification in PowerModels is consistent with the [PGLib-OPF version](https://github.com/power-grid-lib/pglib-opf).  This is the standard formulation for algorithmic benchmarking, which is why we prefer it as the default in this package.  So, yes, this is the desired behavior.

There are plenty of good reasons one might depart from this default and I am sure PandaPower had one such reason in mind. PowerModels provides an easy framework for developing new problem formulations so that one can explore variants like these with a minimum of additional effort.
